# 设置启用的环境
spring:
  profiles:
    active: pub

---
# 公共
spring:
  config:
    activate:
      on-profile: pub
server:
  port: 8080

---
# 开发
server:
  port: 80
spring:
  config:
    activate:
      on-profile: dev
---
# 生产
server:
  port: 81
spring:
  config:
    activate:
      on-profile: pro
---
# 测试
server:
  port: 82
spring:
  config:
    activate:
      on-profile: test